#!/usr/bin/env bash

# Shebang only accept one argument.
#    #!/usr/bin/env bash -e
# wouldn't worked
set -e 

PKG_DIR="$HOME/.pkgs/"

mkdir -p "$PKG_DIR"

case $1 in
    rust|cargo)
        DEST="$PKG_DIR/rust/"
        mkdir -p "$DEST"
        curl https://static.rust-lang.org/rustup.sh | bash -s -- --prefix="$DEST" --disable-sudo
        ;;
    ocaml|opam)
        DEST="$PKG_DIR/ocaml/"
        mkdir -p "$DEST"
        curl https://raw.githubusercontent.com/hcarty/ocamlbrew/master/ocamlbrew-install | env OCAMLBREW_FLAGS="-r -b $DEST" bash
        ;;
    ruby|rails|rvm)
        DEST="$PKG_DIR/rvm"
        curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles --path "$DEST" --user-install stable
        ;;
    otp|erlang|rebar)
        DEST="$PKG_DIR/erlang/"
        mkdir "$DEST"
        # Install erlang itself
        (
            set -e
            cd $(mktemp -d)
            SHA1="4397f29801fd430ef7e9ff03ea814807bf954e20"
            CACHE="/tmp/${SHA1}.tar.gz"
            test -f "$CACHE" || curl -L "http://erlang.org/download/otp_src_18.2.1.tar.gz" -o "$CACHE"
            echo "${SHA1}  $CACHE" | sha1sum -c
            tar -x --strip-components=1 -f "$CACHE"
            ./configure --prefix="$DEST"
            make -j4 all install
        )
        # Install rebar
        (
            set -e
            export PATH="$DEST/bin/:$PATH"
            cd $(mktemp -d)
            curl -L "https://github.com/rebar/rebar/archive/2.6.1.tar.gz" -o rebar.tar.gz
            echo "7f9b799c5dfa06d1779d828c767be2732dacc411  rebar.tar.gz" | sha1sum -c
            tar -x --strip-components=1 -f rebar.tar.gz
            ./bootstrap
            mv ./rebar "$DEST/bin/"
        )
        ;;
    npm|node)
        DEST="$PKG_DIR/node"
        mkdir "$DEST"
        (
            set -e
            cd $(mktemp -d)
            SHA256="083766aff72fc5c78f6999dd0d00bc0340a052ab270fd60d6928b719ca2b3fd1"
            CACHE="/tmp/${SHA256}.tar.xz"
            test -f "$CACHE" || curl "https://nodejs.org/dist/v5.11.0/node-v5.11.0.tar.xz" -o "$CACHE"
            echo "${SHA256}  $CACHE" | sha256sum -c
            tar -x --strip-components=1 -f "$CACHE"
            ./configure --prefix="$DEST"
            make -j4 all install
        )
        ;;
    cabal|haskell)
        # See <https://github.com/haskell/cabal/issues/3003#issuecomment-167577489>
        cabal install --upgrade cabal-install --constraint 'binary < 0.8'
        ;;
    *)
        echo "Pkgs unknown"
        exit 127
esac
