#!/usr/bin/env bash

# Shebang only accept one argument.
#    #!/usr/bin/env bash -e
# wouldn't worked
set -e 

PKG_DIR="$HOME/.pkgs/"

mkdir -p "$PKG_DIR"

case $1 in
    rust|cargo)
        DEST="$PKG_DIR/rust/"
        mkdir -p "$DEST"
        curl https://static.rust-lang.org/rustup.sh | bash -s -- --prefix="$DEST" --disable-sudo
        ;;
    ocaml|opam)
        DEST="$PKG_DIR/ocaml/"
        mkdir -p "$DEST"
        curl https://raw.githubusercontent.com/hcarty/ocamlbrew/master/ocamlbrew-install | env OCAMLBREW_FLAGS="-r -b $DEST" bash
        ;;
    ruby|rails|rvm)
        DEST="$PKG_DIR/rvm"
        curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles --path "$DEST" --user-install stable
        ;;
    otp|erlang|rebar)
        DEST="$PKG_DIR/erlang/"
        mkdir "$DEST"
        # Install erlang itself
        (
            set -e
            cd $(mktemp -d)
            curl -L "http://erlang.org/download/otp_src_18.2.1.tar.gz" -o erlang.tar.gz
            echo "4397f29801fd430ef7e9ff03ea814807bf954e20  erlang.tar.gz" | sha1sum -c
            mkdir -p erlang
            tar -x --strip-components=1 -f erlang.tar.gz -C erlang
            cd erlang
            ./configure --prefix="$DEST"
            make -j4 all install
        )
        # Install rebar
        (
            set -e
            export PATH="$DEST/bin/:$PATH"
            cd $(mktemp -d)
            curl -L "https://github.com/rebar/rebar/archive/2.6.1.tar.gz" -o rebar.tar.gz
            echo "7f9b799c5dfa06d1779d828c767be2732dacc411  rebar.tar.gz" | sha1sum -c
            mkdir -p rebar
            tar -x --strip-components=1 -f rebar.tar.gz -C rebar
            cd rebar
            ./bootstrap
            mv ./rebar "$DEST/bin/"
        )
        ;;
    *)
        echo "Pkgs unknown"
        exit 127
esac
