#!/usr/bin/env sh

set -e

export PATH="$HOME/.local/bin/:$PATH"

usage()
{
    echo "Usage: $0 [-p <interpreter>] [directory]" > /dev/stderr
    exit 127
}

create_venv()
{
    if [ "x${PYTHON}" == "x" ]
    then
        virtualenv "$1"
    else
        virtualenv -p "$PYTHON" "$1"
    fi
    "$1/bin/pip" install --upgrade pip
}

while getopts ":p:" o
do
    case "$o" in
        p)
            PYTHON="${OPTARG}"
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

# Use current dir or the directory speci
if [ "x${1}" = "x" ]
then
    DST="$PWD"
else
    DST=$(readlink -f "$1")
fi

cursor="$DST"
until [ "${cursor}" = "/" ]
do
    if [ -d "${cursor}/.git" ]
    then
        name=$(basename "$cursor")
        venv="${cursor}/.${name}"
        create_venv "$venv"

        ignore_line="/.${name}"
        ignore_file="${cursor}/.git/info/exclude"
        if ! grep "$ignore_line" "$ignore_file" > /dev/null 2> /dev/null
        then
            echo "$ignore_line" >> "$ignore_file"
        fi
        exit 0
    fi
    cursor=$(dirname "$cursor")
done

name=$(basename "$DST")
venv="${DST}/.${name}"
create_venv "$venv"
