#!/usr/bin/env bash

set -eo pipefail

export PATH="$HOME/.local/bin/:$PATH"

usage()
{
    echo "Usage: $0 [-p <interpreter>] [directory]" > /dev/stderr
    exit 127
}

create_venv()
{
    if [ "x${PYTHON}" == "x" ]
    then
        virtualenv "$1"
    else
        virtualenv -p "$PYTHON" "$1"
    fi
    "$1/bin/pip" install --upgrade pip
}

while getopts ":p:" o
do
    case "$o" in
        p)
            PYTHON="${OPTARG}"
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND - 1))

# Use current dir or the directory specified
if [ "x${1}" = "x" ]
then
    DST="$PWD"
else
    DST=$(readlink -f "$1")
fi

REAL_DST="$( (cd "$DST" && git rev-parse --show-toplevel 2> /dev/null) || echo "$DST" )"

name=$(basename "$REAL_DST")
venv="${REAL_DST}/.${name}"
[ -x "${REAL_DST}/.git" ] && (echo "/.${name}" >> "${REAL_DST}/.git/info/exclude")
create_venv "$venv"
